apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
  labels:
    test: stress
spec:
  nodeSelector:
    kubernetes.io/hostname: aks-agentpool-64770781-vmss00000d
  containers:
  - name: cpu-stress
    image: polinux/stress-ng
    command: ["stress-ng"]
    args:
      - "--cpu"
      - "8"
      - "--cpu-load"
      - "100"
      - "--timeout"
      - "0"
