apiVersion: v1
kind: Pod
metadata:
  name: io-stress
  labels:
    test: stress
spec:
  nodeSelector:
    kubernetes.io/hostname: aks-agentpool-64770781-vmss00000d
  containers:
  - name: io-stress
    image: ubuntu:latest
    command: ["/bin/bash"]
    args:
      - "-c"
      - |
        apt-get update && apt-get install -y fio
        while true; do
          fio --name=randwrite --ioengine=libaio --direct=1 --bs=4k --size=4G \
            --numjobs=8 --rw=randwrite --iodepth=64 --runtime=60 --time_based \
            --group_reporting --directory=/mnt/stress
          fio --name=randread --ioengine=libaio --direct=1 --bs=4k --size=4G \
            --numjobs=8 --rw=randread --iodepth=64 --runtime=60 --time_based \
            --group_reporting --directory=/mnt/stress
        done
    volumeMounts:
    - name: test-vol
      mountPath: /mnt/stress
  volumes:
  - name: test-vol
    emptyDir: {}
