apiVersion: v1
kind: Pod
metadata:
  name: memory-stress
  labels:
    test: stress
spec:
  nodeSelector:
    kubernetes.io/hostname: aks-agentpool-64770781-vmss00000d
  containers:
  - name: memory-stress
    image: polinux/stress-ng
    command: ["stress-ng"]
    args:
      - "--vm"
      - "4"
      - "--vm-bytes"
      - "8G"
      - "--vm-keep"
      - "--timeout"
      - "0"
